/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SpecificationRouteImport } from './routes/specification'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SdksRouteImport } from './routes/sdks'
import { Route as ProtocolRouteImport } from './routes/protocol'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ManifestoRouteImport } from './routes/manifesto'
import { Route as ExamplesRouteImport } from './routes/examples'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DocsServeRouteImport } from './routes/docs.serve'
import { Route as DocsSecurityRouteImport } from './routes/docs.security'
import { Route as DocsReceiptsRouteImport } from './routes/docs.receipts'
import { Route as DocsQuickstartRouteImport } from './routes/docs.quickstart'
import { Route as DocsPricingRouteImport } from './routes/docs.pricing'
import { Route as DocsHandshakeRouteImport } from './routes/docs.handshake'
import { Route as DocsFaqRouteImport } from './routes/docs.faq'
import { Route as DocsErrorsRouteImport } from './routes/docs.errors'
import { Route as DocsConceptsRouteImport } from './routes/docs.concepts'
import { Route as DocsClientsRouteImport } from './routes/docs.clients'
import { Route as DocsArchitectureRouteImport } from './routes/docs.architecture'
import { Route as DocsAgentsRouteImport } from './routes/docs.agents'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardResourcesRouteImport } from './routes/dashboard.resources'
import { Route as DashboardPlaygroundRouteImport } from './routes/dashboard.playground'
import { Route as DashboardPaymentsRouteImport } from './routes/dashboard.payments'
import { Route as DashboardDeveloperRouteImport } from './routes/dashboard.developer'
import { Route as DashboardResourcesIndexRouteImport } from './routes/dashboard.resources.index'
import { Route as DashboardResourcesNewRouteImport } from './routes/dashboard.resources.new'
import { Route as DashboardResourcesIdRouteImport } from './routes/dashboard.resources.$id'
import { Route as DashboardResourcesIdIndexRouteImport } from './routes/dashboard.resources.$id.index'
import { Route as DashboardResourcesIdEditRouteImport } from './routes/dashboard.resources.$id.edit'

const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecificationRoute = SpecificationRouteImport.update({
  id: '/specification',
  path: '/specification',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SdksRoute = SdksRouteImport.update({
  id: '/sdks',
  path: '/sdks',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolRoute = ProtocolRouteImport.update({
  id: '/protocol',
  path: '/protocol',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestoRoute = ManifestoRouteImport.update({
  id: '/manifesto',
  path: '/manifesto',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesRoute = ExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DocsServeRoute = DocsServeRouteImport.update({
  id: '/serve',
  path: '/serve',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSecurityRoute = DocsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => DocsRoute,
} as any)
const DocsReceiptsRoute = DocsReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => DocsRoute,
} as any)
const DocsQuickstartRoute = DocsQuickstartRouteImport.update({
  id: '/quickstart',
  path: '/quickstart',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPricingRoute = DocsPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => DocsRoute,
} as any)
const DocsHandshakeRoute = DocsHandshakeRouteImport.update({
  id: '/handshake',
  path: '/handshake',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFaqRoute = DocsFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => DocsRoute,
} as any)
const DocsErrorsRoute = DocsErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => DocsRoute,
} as any)
const DocsConceptsRoute = DocsConceptsRouteImport.update({
  id: '/concepts',
  path: '/concepts',
  getParentRoute: () => DocsRoute,
} as any)
const DocsClientsRoute = DocsClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => DocsRoute,
} as any)
const DocsArchitectureRoute = DocsArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => DocsRoute,
} as any)
const DocsAgentsRoute = DocsAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => DocsRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResourcesRoute = DashboardResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlaygroundRoute = DashboardPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaymentsRoute = DashboardPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDeveloperRoute = DashboardDeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResourcesIndexRoute = DashboardResourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardResourcesRoute,
} as any)
const DashboardResourcesNewRoute = DashboardResourcesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardResourcesRoute,
} as any)
const DashboardResourcesIdRoute = DashboardResourcesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardResourcesRoute,
} as any)
const DashboardResourcesIdIndexRoute =
  DashboardResourcesIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardResourcesIdRoute,
  } as any)
const DashboardResourcesIdEditRoute =
  DashboardResourcesIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => DashboardResourcesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/changelog': typeof ChangelogRoute
  '/console': typeof ConsoleRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/examples': typeof ExamplesRoute
  '/manifesto': typeof ManifestoRoute
  '/pricing': typeof PricingRoute
  '/protocol': typeof ProtocolRoute
  '/sdks': typeof SdksRoute
  '/security': typeof SecurityRoute
  '/sign-in': typeof SignInRoute
  '/specification': typeof SpecificationRoute
  '/status': typeof StatusRoute
  '/dashboard/developer': typeof DashboardDeveloperRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/playground': typeof DashboardPlaygroundRoute
  '/dashboard/resources': typeof DashboardResourcesRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/docs/agents': typeof DocsAgentsRoute
  '/docs/architecture': typeof DocsArchitectureRoute
  '/docs/clients': typeof DocsClientsRoute
  '/docs/concepts': typeof DocsConceptsRoute
  '/docs/errors': typeof DocsErrorsRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/handshake': typeof DocsHandshakeRoute
  '/docs/pricing': typeof DocsPricingRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/receipts': typeof DocsReceiptsRoute
  '/docs/security': typeof DocsSecurityRoute
  '/docs/serve': typeof DocsServeRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/dashboard/resources/$id': typeof DashboardResourcesIdRouteWithChildren
  '/dashboard/resources/new': typeof DashboardResourcesNewRoute
  '/dashboard/resources/': typeof DashboardResourcesIndexRoute
  '/dashboard/resources/$id/edit': typeof DashboardResourcesIdEditRoute
  '/dashboard/resources/$id/': typeof DashboardResourcesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/changelog': typeof ChangelogRoute
  '/console': typeof ConsoleRoute
  '/contact': typeof ContactRoute
  '/examples': typeof ExamplesRoute
  '/manifesto': typeof ManifestoRoute
  '/pricing': typeof PricingRoute
  '/protocol': typeof ProtocolRoute
  '/sdks': typeof SdksRoute
  '/security': typeof SecurityRoute
  '/sign-in': typeof SignInRoute
  '/specification': typeof SpecificationRoute
  '/status': typeof StatusRoute
  '/dashboard/developer': typeof DashboardDeveloperRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/playground': typeof DashboardPlaygroundRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/docs/agents': typeof DocsAgentsRoute
  '/docs/architecture': typeof DocsArchitectureRoute
  '/docs/clients': typeof DocsClientsRoute
  '/docs/concepts': typeof DocsConceptsRoute
  '/docs/errors': typeof DocsErrorsRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/handshake': typeof DocsHandshakeRoute
  '/docs/pricing': typeof DocsPricingRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/receipts': typeof DocsReceiptsRoute
  '/docs/security': typeof DocsSecurityRoute
  '/docs/serve': typeof DocsServeRoute
  '/dashboard': typeof DashboardIndexRoute
  '/docs': typeof DocsIndexRoute
  '/dashboard/resources/new': typeof DashboardResourcesNewRoute
  '/dashboard/resources': typeof DashboardResourcesIndexRoute
  '/dashboard/resources/$id/edit': typeof DashboardResourcesIdEditRoute
  '/dashboard/resources/$id': typeof DashboardResourcesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/changelog': typeof ChangelogRoute
  '/console': typeof ConsoleRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/examples': typeof ExamplesRoute
  '/manifesto': typeof ManifestoRoute
  '/pricing': typeof PricingRoute
  '/protocol': typeof ProtocolRoute
  '/sdks': typeof SdksRoute
  '/security': typeof SecurityRoute
  '/sign-in': typeof SignInRoute
  '/specification': typeof SpecificationRoute
  '/status': typeof StatusRoute
  '/dashboard/developer': typeof DashboardDeveloperRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/playground': typeof DashboardPlaygroundRoute
  '/dashboard/resources': typeof DashboardResourcesRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/docs/agents': typeof DocsAgentsRoute
  '/docs/architecture': typeof DocsArchitectureRoute
  '/docs/clients': typeof DocsClientsRoute
  '/docs/concepts': typeof DocsConceptsRoute
  '/docs/errors': typeof DocsErrorsRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/handshake': typeof DocsHandshakeRoute
  '/docs/pricing': typeof DocsPricingRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/receipts': typeof DocsReceiptsRoute
  '/docs/security': typeof DocsSecurityRoute
  '/docs/serve': typeof DocsServeRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/dashboard/resources/$id': typeof DashboardResourcesIdRouteWithChildren
  '/dashboard/resources/new': typeof DashboardResourcesNewRoute
  '/dashboard/resources/': typeof DashboardResourcesIndexRoute
  '/dashboard/resources/$id/edit': typeof DashboardResourcesIdEditRoute
  '/dashboard/resources/$id/': typeof DashboardResourcesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/changelog'
    | '/console'
    | '/contact'
    | '/dashboard'
    | '/docs'
    | '/examples'
    | '/manifesto'
    | '/pricing'
    | '/protocol'
    | '/sdks'
    | '/security'
    | '/sign-in'
    | '/specification'
    | '/status'
    | '/dashboard/developer'
    | '/dashboard/payments'
    | '/dashboard/playground'
    | '/dashboard/resources'
    | '/dashboard/settings'
    | '/docs/agents'
    | '/docs/architecture'
    | '/docs/clients'
    | '/docs/concepts'
    | '/docs/errors'
    | '/docs/faq'
    | '/docs/handshake'
    | '/docs/pricing'
    | '/docs/quickstart'
    | '/docs/receipts'
    | '/docs/security'
    | '/docs/serve'
    | '/dashboard/'
    | '/docs/'
    | '/dashboard/resources/$id'
    | '/dashboard/resources/new'
    | '/dashboard/resources/'
    | '/dashboard/resources/$id/edit'
    | '/dashboard/resources/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/changelog'
    | '/console'
    | '/contact'
    | '/examples'
    | '/manifesto'
    | '/pricing'
    | '/protocol'
    | '/sdks'
    | '/security'
    | '/sign-in'
    | '/specification'
    | '/status'
    | '/dashboard/developer'
    | '/dashboard/payments'
    | '/dashboard/playground'
    | '/dashboard/settings'
    | '/docs/agents'
    | '/docs/architecture'
    | '/docs/clients'
    | '/docs/concepts'
    | '/docs/errors'
    | '/docs/faq'
    | '/docs/handshake'
    | '/docs/pricing'
    | '/docs/quickstart'
    | '/docs/receipts'
    | '/docs/security'
    | '/docs/serve'
    | '/dashboard'
    | '/docs'
    | '/dashboard/resources/new'
    | '/dashboard/resources'
    | '/dashboard/resources/$id/edit'
    | '/dashboard/resources/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/changelog'
    | '/console'
    | '/contact'
    | '/dashboard'
    | '/docs'
    | '/examples'
    | '/manifesto'
    | '/pricing'
    | '/protocol'
    | '/sdks'
    | '/security'
    | '/sign-in'
    | '/specification'
    | '/status'
    | '/dashboard/developer'
    | '/dashboard/payments'
    | '/dashboard/playground'
    | '/dashboard/resources'
    | '/dashboard/settings'
    | '/docs/agents'
    | '/docs/architecture'
    | '/docs/clients'
    | '/docs/concepts'
    | '/docs/errors'
    | '/docs/faq'
    | '/docs/handshake'
    | '/docs/pricing'
    | '/docs/quickstart'
    | '/docs/receipts'
    | '/docs/security'
    | '/docs/serve'
    | '/dashboard/'
    | '/docs/'
    | '/dashboard/resources/$id'
    | '/dashboard/resources/new'
    | '/dashboard/resources/'
    | '/dashboard/resources/$id/edit'
    | '/dashboard/resources/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  CareersRoute: typeof CareersRoute
  ChangelogRoute: typeof ChangelogRoute
  ConsoleRoute: typeof ConsoleRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  ExamplesRoute: typeof ExamplesRoute
  ManifestoRoute: typeof ManifestoRoute
  PricingRoute: typeof PricingRoute
  ProtocolRoute: typeof ProtocolRoute
  SdksRoute: typeof SdksRoute
  SecurityRoute: typeof SecurityRoute
  SignInRoute: typeof SignInRoute
  SpecificationRoute: typeof SpecificationRoute
  StatusRoute: typeof StatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specification': {
      id: '/specification'
      path: '/specification'
      fullPath: '/specification'
      preLoaderRoute: typeof SpecificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sdks': {
      id: '/sdks'
      path: '/sdks'
      fullPath: '/sdks'
      preLoaderRoute: typeof SdksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocol': {
      id: '/protocol'
      path: '/protocol'
      fullPath: '/protocol'
      preLoaderRoute: typeof ProtocolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifesto': {
      id: '/manifesto'
      path: '/manifesto'
      fullPath: '/manifesto'
      preLoaderRoute: typeof ManifestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples': {
      id: '/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/docs/serve': {
      id: '/docs/serve'
      path: '/serve'
      fullPath: '/docs/serve'
      preLoaderRoute: typeof DocsServeRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/security': {
      id: '/docs/security'
      path: '/security'
      fullPath: '/docs/security'
      preLoaderRoute: typeof DocsSecurityRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/receipts': {
      id: '/docs/receipts'
      path: '/receipts'
      fullPath: '/docs/receipts'
      preLoaderRoute: typeof DocsReceiptsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/quickstart': {
      id: '/docs/quickstart'
      path: '/quickstart'
      fullPath: '/docs/quickstart'
      preLoaderRoute: typeof DocsQuickstartRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/pricing': {
      id: '/docs/pricing'
      path: '/pricing'
      fullPath: '/docs/pricing'
      preLoaderRoute: typeof DocsPricingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/handshake': {
      id: '/docs/handshake'
      path: '/handshake'
      fullPath: '/docs/handshake'
      preLoaderRoute: typeof DocsHandshakeRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/faq': {
      id: '/docs/faq'
      path: '/faq'
      fullPath: '/docs/faq'
      preLoaderRoute: typeof DocsFaqRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/errors': {
      id: '/docs/errors'
      path: '/errors'
      fullPath: '/docs/errors'
      preLoaderRoute: typeof DocsErrorsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/concepts': {
      id: '/docs/concepts'
      path: '/concepts'
      fullPath: '/docs/concepts'
      preLoaderRoute: typeof DocsConceptsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/clients': {
      id: '/docs/clients'
      path: '/clients'
      fullPath: '/docs/clients'
      preLoaderRoute: typeof DocsClientsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/architecture': {
      id: '/docs/architecture'
      path: '/architecture'
      fullPath: '/docs/architecture'
      preLoaderRoute: typeof DocsArchitectureRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/agents': {
      id: '/docs/agents'
      path: '/agents'
      fullPath: '/docs/agents'
      preLoaderRoute: typeof DocsAgentsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/resources': {
      id: '/dashboard/resources'
      path: '/resources'
      fullPath: '/dashboard/resources'
      preLoaderRoute: typeof DashboardResourcesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/playground': {
      id: '/dashboard/playground'
      path: '/playground'
      fullPath: '/dashboard/playground'
      preLoaderRoute: typeof DashboardPlaygroundRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payments': {
      id: '/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof DashboardPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/developer': {
      id: '/dashboard/developer'
      path: '/developer'
      fullPath: '/dashboard/developer'
      preLoaderRoute: typeof DashboardDeveloperRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/resources/': {
      id: '/dashboard/resources/'
      path: '/'
      fullPath: '/dashboard/resources/'
      preLoaderRoute: typeof DashboardResourcesIndexRouteImport
      parentRoute: typeof DashboardResourcesRoute
    }
    '/dashboard/resources/new': {
      id: '/dashboard/resources/new'
      path: '/new'
      fullPath: '/dashboard/resources/new'
      preLoaderRoute: typeof DashboardResourcesNewRouteImport
      parentRoute: typeof DashboardResourcesRoute
    }
    '/dashboard/resources/$id': {
      id: '/dashboard/resources/$id'
      path: '/$id'
      fullPath: '/dashboard/resources/$id'
      preLoaderRoute: typeof DashboardResourcesIdRouteImport
      parentRoute: typeof DashboardResourcesRoute
    }
    '/dashboard/resources/$id/': {
      id: '/dashboard/resources/$id/'
      path: '/'
      fullPath: '/dashboard/resources/$id/'
      preLoaderRoute: typeof DashboardResourcesIdIndexRouteImport
      parentRoute: typeof DashboardResourcesIdRoute
    }
    '/dashboard/resources/$id/edit': {
      id: '/dashboard/resources/$id/edit'
      path: '/edit'
      fullPath: '/dashboard/resources/$id/edit'
      preLoaderRoute: typeof DashboardResourcesIdEditRouteImport
      parentRoute: typeof DashboardResourcesIdRoute
    }
  }
}

interface DashboardResourcesIdRouteChildren {
  DashboardResourcesIdEditRoute: typeof DashboardResourcesIdEditRoute
  DashboardResourcesIdIndexRoute: typeof DashboardResourcesIdIndexRoute
}

const DashboardResourcesIdRouteChildren: DashboardResourcesIdRouteChildren = {
  DashboardResourcesIdEditRoute: DashboardResourcesIdEditRoute,
  DashboardResourcesIdIndexRoute: DashboardResourcesIdIndexRoute,
}

const DashboardResourcesIdRouteWithChildren =
  DashboardResourcesIdRoute._addFileChildren(DashboardResourcesIdRouteChildren)

interface DashboardResourcesRouteChildren {
  DashboardResourcesIdRoute: typeof DashboardResourcesIdRouteWithChildren
  DashboardResourcesNewRoute: typeof DashboardResourcesNewRoute
  DashboardResourcesIndexRoute: typeof DashboardResourcesIndexRoute
}

const DashboardResourcesRouteChildren: DashboardResourcesRouteChildren = {
  DashboardResourcesIdRoute: DashboardResourcesIdRouteWithChildren,
  DashboardResourcesNewRoute: DashboardResourcesNewRoute,
  DashboardResourcesIndexRoute: DashboardResourcesIndexRoute,
}

const DashboardResourcesRouteWithChildren =
  DashboardResourcesRoute._addFileChildren(DashboardResourcesRouteChildren)

interface DashboardRouteChildren {
  DashboardDeveloperRoute: typeof DashboardDeveloperRoute
  DashboardPaymentsRoute: typeof DashboardPaymentsRoute
  DashboardPlaygroundRoute: typeof DashboardPlaygroundRoute
  DashboardResourcesRoute: typeof DashboardResourcesRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDeveloperRoute: DashboardDeveloperRoute,
  DashboardPaymentsRoute: DashboardPaymentsRoute,
  DashboardPlaygroundRoute: DashboardPlaygroundRoute,
  DashboardResourcesRoute: DashboardResourcesRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface DocsRouteChildren {
  DocsAgentsRoute: typeof DocsAgentsRoute
  DocsArchitectureRoute: typeof DocsArchitectureRoute
  DocsClientsRoute: typeof DocsClientsRoute
  DocsConceptsRoute: typeof DocsConceptsRoute
  DocsErrorsRoute: typeof DocsErrorsRoute
  DocsFaqRoute: typeof DocsFaqRoute
  DocsHandshakeRoute: typeof DocsHandshakeRoute
  DocsPricingRoute: typeof DocsPricingRoute
  DocsQuickstartRoute: typeof DocsQuickstartRoute
  DocsReceiptsRoute: typeof DocsReceiptsRoute
  DocsSecurityRoute: typeof DocsSecurityRoute
  DocsServeRoute: typeof DocsServeRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsAgentsRoute: DocsAgentsRoute,
  DocsArchitectureRoute: DocsArchitectureRoute,
  DocsClientsRoute: DocsClientsRoute,
  DocsConceptsRoute: DocsConceptsRoute,
  DocsErrorsRoute: DocsErrorsRoute,
  DocsFaqRoute: DocsFaqRoute,
  DocsHandshakeRoute: DocsHandshakeRoute,
  DocsPricingRoute: DocsPricingRoute,
  DocsQuickstartRoute: DocsQuickstartRoute,
  DocsReceiptsRoute: DocsReceiptsRoute,
  DocsSecurityRoute: DocsSecurityRoute,
  DocsServeRoute: DocsServeRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  CareersRoute: CareersRoute,
  ChangelogRoute: ChangelogRoute,
  ConsoleRoute: ConsoleRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  ExamplesRoute: ExamplesRoute,
  ManifestoRoute: ManifestoRoute,
  PricingRoute: PricingRoute,
  ProtocolRoute: ProtocolRoute,
  SdksRoute: SdksRoute,
  SecurityRoute: SecurityRoute,
  SignInRoute: SignInRoute,
  SpecificationRoute: SpecificationRoute,
  StatusRoute: StatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
