/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtocolRouteImport } from './routes/protocol'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsServeRouteImport } from './routes/docs.serve'
import { Route as DocsSecurityRouteImport } from './routes/docs.security'
import { Route as DocsReceiptsRouteImport } from './routes/docs.receipts'
import { Route as DocsQuickstartRouteImport } from './routes/docs.quickstart'
import { Route as DocsPricingRouteImport } from './routes/docs.pricing'
import { Route as DocsHandshakeRouteImport } from './routes/docs.handshake'
import { Route as DocsFaqRouteImport } from './routes/docs.faq'
import { Route as DocsErrorsRouteImport } from './routes/docs.errors'
import { Route as DocsConceptsRouteImport } from './routes/docs.concepts'
import { Route as DocsClientsRouteImport } from './routes/docs.clients'
import { Route as DocsArchitectureRouteImport } from './routes/docs.architecture'
import { Route as DocsAgentsRouteImport } from './routes/docs.agents'

const ProtocolRoute = ProtocolRouteImport.update({
  id: '/protocol',
  path: '/protocol',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsServeRoute = DocsServeRouteImport.update({
  id: '/serve',
  path: '/serve',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSecurityRoute = DocsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => DocsRoute,
} as any)
const DocsReceiptsRoute = DocsReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => DocsRoute,
} as any)
const DocsQuickstartRoute = DocsQuickstartRouteImport.update({
  id: '/quickstart',
  path: '/quickstart',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPricingRoute = DocsPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => DocsRoute,
} as any)
const DocsHandshakeRoute = DocsHandshakeRouteImport.update({
  id: '/handshake',
  path: '/handshake',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFaqRoute = DocsFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => DocsRoute,
} as any)
const DocsErrorsRoute = DocsErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => DocsRoute,
} as any)
const DocsConceptsRoute = DocsConceptsRouteImport.update({
  id: '/concepts',
  path: '/concepts',
  getParentRoute: () => DocsRoute,
} as any)
const DocsClientsRoute = DocsClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => DocsRoute,
} as any)
const DocsArchitectureRoute = DocsArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => DocsRoute,
} as any)
const DocsAgentsRoute = DocsAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/console': typeof ConsoleRoute
  '/docs': typeof DocsRouteWithChildren
  '/pricing': typeof PricingRoute
  '/protocol': typeof ProtocolRoute
  '/docs/agents': typeof DocsAgentsRoute
  '/docs/architecture': typeof DocsArchitectureRoute
  '/docs/clients': typeof DocsClientsRoute
  '/docs/concepts': typeof DocsConceptsRoute
  '/docs/errors': typeof DocsErrorsRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/handshake': typeof DocsHandshakeRoute
  '/docs/pricing': typeof DocsPricingRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/receipts': typeof DocsReceiptsRoute
  '/docs/security': typeof DocsSecurityRoute
  '/docs/serve': typeof DocsServeRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/console': typeof ConsoleRoute
  '/pricing': typeof PricingRoute
  '/protocol': typeof ProtocolRoute
  '/docs/agents': typeof DocsAgentsRoute
  '/docs/architecture': typeof DocsArchitectureRoute
  '/docs/clients': typeof DocsClientsRoute
  '/docs/concepts': typeof DocsConceptsRoute
  '/docs/errors': typeof DocsErrorsRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/handshake': typeof DocsHandshakeRoute
  '/docs/pricing': typeof DocsPricingRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/receipts': typeof DocsReceiptsRoute
  '/docs/security': typeof DocsSecurityRoute
  '/docs/serve': typeof DocsServeRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/console': typeof ConsoleRoute
  '/docs': typeof DocsRouteWithChildren
  '/pricing': typeof PricingRoute
  '/protocol': typeof ProtocolRoute
  '/docs/agents': typeof DocsAgentsRoute
  '/docs/architecture': typeof DocsArchitectureRoute
  '/docs/clients': typeof DocsClientsRoute
  '/docs/concepts': typeof DocsConceptsRoute
  '/docs/errors': typeof DocsErrorsRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/handshake': typeof DocsHandshakeRoute
  '/docs/pricing': typeof DocsPricingRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/receipts': typeof DocsReceiptsRoute
  '/docs/security': typeof DocsSecurityRoute
  '/docs/serve': typeof DocsServeRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/changelog'
    | '/console'
    | '/docs'
    | '/pricing'
    | '/protocol'
    | '/docs/agents'
    | '/docs/architecture'
    | '/docs/clients'
    | '/docs/concepts'
    | '/docs/errors'
    | '/docs/faq'
    | '/docs/handshake'
    | '/docs/pricing'
    | '/docs/quickstart'
    | '/docs/receipts'
    | '/docs/security'
    | '/docs/serve'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changelog'
    | '/console'
    | '/pricing'
    | '/protocol'
    | '/docs/agents'
    | '/docs/architecture'
    | '/docs/clients'
    | '/docs/concepts'
    | '/docs/errors'
    | '/docs/faq'
    | '/docs/handshake'
    | '/docs/pricing'
    | '/docs/quickstart'
    | '/docs/receipts'
    | '/docs/security'
    | '/docs/serve'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/changelog'
    | '/console'
    | '/docs'
    | '/pricing'
    | '/protocol'
    | '/docs/agents'
    | '/docs/architecture'
    | '/docs/clients'
    | '/docs/concepts'
    | '/docs/errors'
    | '/docs/faq'
    | '/docs/handshake'
    | '/docs/pricing'
    | '/docs/quickstart'
    | '/docs/receipts'
    | '/docs/security'
    | '/docs/serve'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangelogRoute: typeof ChangelogRoute
  ConsoleRoute: typeof ConsoleRoute
  DocsRoute: typeof DocsRouteWithChildren
  PricingRoute: typeof PricingRoute
  ProtocolRoute: typeof ProtocolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/protocol': {
      id: '/protocol'
      path: '/protocol'
      fullPath: '/protocol'
      preLoaderRoute: typeof ProtocolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/serve': {
      id: '/docs/serve'
      path: '/serve'
      fullPath: '/docs/serve'
      preLoaderRoute: typeof DocsServeRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/security': {
      id: '/docs/security'
      path: '/security'
      fullPath: '/docs/security'
      preLoaderRoute: typeof DocsSecurityRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/receipts': {
      id: '/docs/receipts'
      path: '/receipts'
      fullPath: '/docs/receipts'
      preLoaderRoute: typeof DocsReceiptsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/quickstart': {
      id: '/docs/quickstart'
      path: '/quickstart'
      fullPath: '/docs/quickstart'
      preLoaderRoute: typeof DocsQuickstartRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/pricing': {
      id: '/docs/pricing'
      path: '/pricing'
      fullPath: '/docs/pricing'
      preLoaderRoute: typeof DocsPricingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/handshake': {
      id: '/docs/handshake'
      path: '/handshake'
      fullPath: '/docs/handshake'
      preLoaderRoute: typeof DocsHandshakeRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/faq': {
      id: '/docs/faq'
      path: '/faq'
      fullPath: '/docs/faq'
      preLoaderRoute: typeof DocsFaqRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/errors': {
      id: '/docs/errors'
      path: '/errors'
      fullPath: '/docs/errors'
      preLoaderRoute: typeof DocsErrorsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/concepts': {
      id: '/docs/concepts'
      path: '/concepts'
      fullPath: '/docs/concepts'
      preLoaderRoute: typeof DocsConceptsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/clients': {
      id: '/docs/clients'
      path: '/clients'
      fullPath: '/docs/clients'
      preLoaderRoute: typeof DocsClientsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/architecture': {
      id: '/docs/architecture'
      path: '/architecture'
      fullPath: '/docs/architecture'
      preLoaderRoute: typeof DocsArchitectureRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/agents': {
      id: '/docs/agents'
      path: '/agents'
      fullPath: '/docs/agents'
      preLoaderRoute: typeof DocsAgentsRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsAgentsRoute: typeof DocsAgentsRoute
  DocsArchitectureRoute: typeof DocsArchitectureRoute
  DocsClientsRoute: typeof DocsClientsRoute
  DocsConceptsRoute: typeof DocsConceptsRoute
  DocsErrorsRoute: typeof DocsErrorsRoute
  DocsFaqRoute: typeof DocsFaqRoute
  DocsHandshakeRoute: typeof DocsHandshakeRoute
  DocsPricingRoute: typeof DocsPricingRoute
  DocsQuickstartRoute: typeof DocsQuickstartRoute
  DocsReceiptsRoute: typeof DocsReceiptsRoute
  DocsSecurityRoute: typeof DocsSecurityRoute
  DocsServeRoute: typeof DocsServeRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsAgentsRoute: DocsAgentsRoute,
  DocsArchitectureRoute: DocsArchitectureRoute,
  DocsClientsRoute: DocsClientsRoute,
  DocsConceptsRoute: DocsConceptsRoute,
  DocsErrorsRoute: DocsErrorsRoute,
  DocsFaqRoute: DocsFaqRoute,
  DocsHandshakeRoute: DocsHandshakeRoute,
  DocsPricingRoute: DocsPricingRoute,
  DocsQuickstartRoute: DocsQuickstartRoute,
  DocsReceiptsRoute: DocsReceiptsRoute,
  DocsSecurityRoute: DocsSecurityRoute,
  DocsServeRoute: DocsServeRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangelogRoute: ChangelogRoute,
  ConsoleRoute: ConsoleRoute,
  DocsRoute: DocsRouteWithChildren,
  PricingRoute: PricingRoute,
  ProtocolRoute: ProtocolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
