/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsServeRouteImport } from './routes/docs.serve'
import { Route as DocsReceiptsRouteImport } from './routes/docs.receipts'
import { Route as DocsPricingRouteImport } from './routes/docs.pricing'
import { Route as DocsHandshakeRouteImport } from './routes/docs.handshake'
import { Route as DocsClientsRouteImport } from './routes/docs.clients'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsServeRoute = DocsServeRouteImport.update({
  id: '/serve',
  path: '/serve',
  getParentRoute: () => DocsRoute,
} as any)
const DocsReceiptsRoute = DocsReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPricingRoute = DocsPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => DocsRoute,
} as any)
const DocsHandshakeRoute = DocsHandshakeRouteImport.update({
  id: '/handshake',
  path: '/handshake',
  getParentRoute: () => DocsRoute,
} as any)
const DocsClientsRoute = DocsClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/clients': typeof DocsClientsRoute
  '/docs/handshake': typeof DocsHandshakeRoute
  '/docs/pricing': typeof DocsPricingRoute
  '/docs/receipts': typeof DocsReceiptsRoute
  '/docs/serve': typeof DocsServeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/clients': typeof DocsClientsRoute
  '/docs/handshake': typeof DocsHandshakeRoute
  '/docs/pricing': typeof DocsPricingRoute
  '/docs/receipts': typeof DocsReceiptsRoute
  '/docs/serve': typeof DocsServeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/clients': typeof DocsClientsRoute
  '/docs/handshake': typeof DocsHandshakeRoute
  '/docs/pricing': typeof DocsPricingRoute
  '/docs/receipts': typeof DocsReceiptsRoute
  '/docs/serve': typeof DocsServeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/docs/clients'
    | '/docs/handshake'
    | '/docs/pricing'
    | '/docs/receipts'
    | '/docs/serve'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/docs/clients'
    | '/docs/handshake'
    | '/docs/pricing'
    | '/docs/receipts'
    | '/docs/serve'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/docs/clients'
    | '/docs/handshake'
    | '/docs/pricing'
    | '/docs/receipts'
    | '/docs/serve'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/serve': {
      id: '/docs/serve'
      path: '/serve'
      fullPath: '/docs/serve'
      preLoaderRoute: typeof DocsServeRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/receipts': {
      id: '/docs/receipts'
      path: '/receipts'
      fullPath: '/docs/receipts'
      preLoaderRoute: typeof DocsReceiptsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/pricing': {
      id: '/docs/pricing'
      path: '/pricing'
      fullPath: '/docs/pricing'
      preLoaderRoute: typeof DocsPricingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/handshake': {
      id: '/docs/handshake'
      path: '/handshake'
      fullPath: '/docs/handshake'
      preLoaderRoute: typeof DocsHandshakeRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/clients': {
      id: '/docs/clients'
      path: '/clients'
      fullPath: '/docs/clients'
      preLoaderRoute: typeof DocsClientsRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsClientsRoute: typeof DocsClientsRoute
  DocsHandshakeRoute: typeof DocsHandshakeRoute
  DocsPricingRoute: typeof DocsPricingRoute
  DocsReceiptsRoute: typeof DocsReceiptsRoute
  DocsServeRoute: typeof DocsServeRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsClientsRoute: DocsClientsRoute,
  DocsHandshakeRoute: DocsHandshakeRoute,
  DocsPricingRoute: DocsPricingRoute,
  DocsReceiptsRoute: DocsReceiptsRoute,
  DocsServeRoute: DocsServeRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
